stages:
  - build
  - deploy

jupyter-build:
  stage: build
  image: python:3.10-slim
  script:
    - pip install -U jupyter-book matplotlib numpy
    - rm -rf _build
    # list folders with notebooks here. Notebooks must be present in _toc.yml
    - jupyter-book clean .
    - jupyter-book build .
    - rm -r public
    # Copy built site to docs
    - cp -r _build/html public
    #- cp -r website/_build/html docs
    #- rm -r website/_build
    # Move figs to built website
    #- rm -rf docs/content/figs
    #- mv website/content/figs docs/content
    # Remove copied folders
    #- rm -rf website/content
    # No Jekyll on remote server
    - touch docs/.nojekyll
  artifacts:
    paths:
      - public/

pages:
  stage: deploy
  only:
    - main
  image: busybox:latest
  artifacts:
    paths:
      - public


